language: objective-c
xcode_workspace: Provenance.xcworkspace # path to your xcodeproj folder

language: objective-c
osx_image: xcode9.4

cache:
  directories:
  - Carthage
  - PVSupport/Carthage

# branches:
#   only:
#     - develop
#     - master
env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - CONFIGURATION="Release"
    - AWS_REGION="us-east-1"
    - AWS_ENDPOINT="http://provenance.joemattiello.com:9000"
matrix:
  include:
    - xcode_scheme: Provenance-Travis
      xcode_sdk: iphonesimulator11.4
      env: DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone X"
    - xcode_scheme: ProvenanceTV-Release
      xcode_sdk: appletvsimulator11.4
      env: DESTINATION="platform=tvOS Simulator,OS=11.4,name=Apple TV"
before_install:
  # gem install xcpretty -N
  # gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - brew outdated carthage || brew upgrade carthage
  - brew install blender/homebrew-tap/rome
before_script:
  # bootstrap the dependencies for the project
        # Output something every 10 minutes or Travis kills the job
    - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
      # This can take a while so using the above to not make travis abort
    - ./Scripts/rome-travis.sh > /tmp/carthage.log
    #- carthage bootstrap --no-use-binaries --platform iOS,tvOS --cache-builds --project-directory "./" --configuration $CONFIGURATION > /tmp/carthage.log
        # Killing background sleep loop
    - kill %1
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  # Test code covered, add -enableCodeCoverage YES to xcodebuild
  #- sleep 5
  #- bash <(curl -s https://codecov.io/bash)
after_failure:
  - tail -100 /tmp/carthage.log
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
script:
  - set -o pipefail
  - swiftlint
  - travis_wait 60 xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme $TRAVIS_XCODE_SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -sdk "$TRAVIS_XCODE_SDK" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO #| xcpretty -f `xcpretty-travis-formatter`
