lane :beta do
  get_certificates(
    development: true,
    username: ENV["APPLE_ID"],
    team_id: ENV["DEV_TEAM_ID"]
  )           # invokes cert
  get_provisioning_profile   # invokes sigh
  build_app(scheme: "Provenance")
  upload_to_testflight
  slack(message: "Successfully distributed a new beta build")
end
