// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Tue Aug 14 18:40:09 CEST 2018
//      user wwwb23prodtminfo
//      for build target ProvenanceTV
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

public let kAppVersion : String = "1.5"
public let kGITRevisionNumber : String = "2099"
public let kGITTag : String = "1.4-1282-g363ef106-dirty"
public let kGITDate : String = "Tue Aug 14 18:37:10 2018"
public let kGITBranch : String = "feature/Core-Beetle-Saturn"
public let kAppBuildConfiguration : String  = "Debug"

public let gitrevision          = "2099"
public let gittag               = "1.4-1282-g363ef106-dirty"
public let gitdate              = "Tue Aug 14 18:37:10 2018"
public let gitbranch            = "feature/Core-Beetle-Saturn"
public let appversion           = "1.5"
public let buildconfiguration   = "Debug"
// public let compiletime          = __TIME__
// public let compiledate          = __DATE__

// Diagnostic info
/*
    Info.plist path:/Users/wwwb23prodtminfo/NetBeansProjects/Provenance/ProvenanceTV/Info.plist
    PWD : /Users/wwwb23prodtminfo/NetBeansProjects/Provenance
    XCode version 9F2000
    PATH : /opt/local/bin:/opt/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
*/
