// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Tue Oct 23 22:20:21 CEST 2018
//      user wwwb23prodtminfo
//      for build target ProvenanceTV
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

public let kAppVersion : String = "1.5"
public let kGITRevisionNumber : String = "2132"
public let kGITTag : String = "1.4-1315-g27a789efd"
public let kGITDate : String = "Tue Oct 23 21:40:19 2018"
public let kGITBranch : String = "feature/add-dyn-sdl-cartfile"
public let kAppBuildConfiguration : String  = "Release"

public let gitrevision          = "2132"
public let gittag               = "1.4-1315-g27a789efd"
public let gitdate              = "Tue Oct 23 21:40:19 2018"
public let gitbranch            = "feature/add-dyn-sdl-cartfile"
public let appversion           = "1.5"
public let buildconfiguration   = "Release"
// public let compiletime          = __TIME__
// public let compiledate          = __DATE__

// Diagnostic info
/*
    Info.plist path:/Users/wwwb23prodtminfo/NetBeansProjects/Provenance/ProvenanceTV/Info.plist
    PWD : /Users/wwwb23prodtminfo/NetBeansProjects/Provenance
    XCode version 10A255
    PATH : /opt/local/bin:/opt/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/wwwb23prodtminfo/.fastlane/bin/bundle/bin:/Library/Ruby/Gems/2.3.0/bin:/Users/wwwb23prodtminfo/.fastlane/bin:/usr/local/opt/mysql@5.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
*/
