
// Do not edit!  This file was autogenerated
//      by ./Provenance/Resources/createVersionHeader.sh
//      on Sun Jul  8 20:44:25 CEST 2018
//      user wwwb23prodtminfo
//      for build target Provenance
//
// gitrevision and gitdate are as reported by git at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>

static NSString* const kAppVersion              = @"1.5";
static NSString* const kGITRevisionNumber       = @"1783";
static NSString* const kGITTag                  = @"1.4-966-g3cfa4f32";
static NSString* const kGITDate                 = @"Sun Jul 8 20:07:03 2018";
static NSString* const kGITBranch               = @"feature/Core-Beetle-Saturn";
static NSString* const kAppBuildConfiguration   = @"Release";

// Suppress warnings incase you choose not to use these variables
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused"

static const char* gitrevision          = "1783";
static const char* gittag               = "1.4-966-g3cfa4f32";
static const char* gitdate              = "Sun Jul 8 20:07:03 2018";
static const char* gitbranch            = "feature/Core-Beetle-Saturn";
static const char* appversion           = "1.5";
static const char* buildconfiguration   = "Release";
static const char* compiletime          = __TIME__;
static const char* compiledate          = __DATE__;

#pragma GCC diagnostic pop

// Diagnostic info
/*
    Info.plist path:/Users/wwwb23prodtminfo/NetBeansProjects/Provenance/Provenance/Provenance-Info.plist
    PWD : /Users/wwwb23prodtminfo/NetBeansProjects/Provenance
    XCode version 9F2000
    PATH : /opt/local/bin:/opt/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
*/

